### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by Nardo021** [UknownPerson/Dot#1]
给个建议，把build好的artifact发布release，因为我不想构建（很懒）

**Comment by UknownPerson** [comment]
5月7日将会推出0.2版本，同时也会发布release


UknownPerson
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "UknownPerson/Dot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 下午4:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[UknownPerson/Dot] 你好 (Issue #1)





 
给个建议，把build好的artifact发布release，因为我不想构建（很懒）

**Comment by Nardo021** [comment]
好的支持，，可以加QQ不 :)

**Comment by UknownPerson** [comment]
行，1785618795




UknownPerson
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "UknownPerson/Dot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [UknownPerson/Dot] 你好 (Issue #1)





 
好的支持，，可以加QQ不 :)

**Comment by Nardo021** [comment]
ok
